---
title: "compare"
output: html_document
date: '2022-07-12'
---

```{r}
source("2D_CFO_MTD.R")
source("pocrm.R")
library(dfcomb)
library(pocrm)
library(parallel)

#Specifiy the possible orderings from Section 3.3.
orders<-matrix(nrow=6,ncol=15)
orders[1,]<-c(1,4,7,10,13,2,5,8,11,14,3,6,9,12,15)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
orders[3,]<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)
orders[4,]<-c(1,4,2,7,5,3,10,8,6,13,11,9,14,12,15)
orders[5,]<-c(1,2,4,7,5,3,6,8,10,13,11,9,12,14,15)
orders[6,]<-c(1,4,2,3,5,7,10,8,6,9,11,13,14,12,15)

#Specify the skeleton values.
skeleton<-getprior(0.03,0.30,13,15)

#Initial guesses of toxicity probabilities for each ordering.
alpha<-getwm(orders,skeleton)

#We consider all orders to be equally likely prior to the study.
prior.o<-rep(1/6,3)

getmode <- function(v) {
 uniqv <- unique(v)
 uniqv[which.max(tabulate(match(v, uniqv)))]
}


target <- 0.30
ncohort <- 20
cohortsize <- 3
init.level.A <- 1
init.level.B <- 1
n.cores <- detectCores()
prior_a1 = c(0.1, 0.2, 0.3)
prior_a2 = c(0.1, 0.2, 0.3, 0.4, 0.5)
prior_tox_a1 = c(0.2, 0.3, 0.4)
prior_tox_a2 = c(0.1, 0.2, 0.3, 0.4, 0.5)
order <- c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)
seeds <- 1:5000

add.args <- list(alp.prior=target, bet.prior=1-target)
```


```{r}
p.trues.1 <- list()
p.trues.1[[1]] <- c(0.05, 0.10, 0.15, 0.30, 0.45)
p.trues.1[[2]] <- c(0.10, 0.15, 0.30, 0.45, 0.55)
p.trues.1[[3]] <- c(0.15, 0.30, 0.45, 0.50, 0.60)
p.true.1 <- rbind(p.trues.1[[1]],p.trues.1[[2]],p.trues.1[[3]])


p.trues.2 <- list()
p.trues.2[[1]] <- c(0.15, 0.30, 0.45, 0.50, 0.60)
p.trues.2[[2]] <- c(0.30, 0.45, 0.50, 0.60, 0.75)
p.trues.2[[3]] <- c(0.45, 0.55, 0.60, 0.70, 0.80)
p.true.2 <- rbind(p.trues.2[[1]],p.trues.2[[2]],p.trues.2[[3]])


p.trues.3 <- list()
p.trues.3[[1]] <- c(0.02, 0.07, 0.10, 0.15, 0.30)
p.trues.3[[2]] <- c(0.07, 0.10, 0.15, 0.30, 0.45)
p.trues.3[[3]] <- c(0.10, 0.15, 0.30, 0.45, 0.55)
p.true.3 <- rbind(p.trues.3[[1]],p.trues.3[[2]],p.trues.3[[3]])


p.trues.4 <- list()
p.trues.4[[1]] <- c(0.30, 0.45, 0.60, 0.70, 0.80)
p.trues.4[[2]] <- c(0.45, 0.55, 0.65, 0.75, 0.85)
p.trues.4[[3]] <- c(0.50, 0.60, 0.70, 0.80, 0.90)
p.true.4 <- rbind(p.trues.4[[1]],p.trues.4[[2]],p.trues.4[[3]])


p.trues.5 <- list()
p.trues.5[[1]] <- c(0.01, 0.02, 0.08, 0.10, 0.11)
p.trues.5[[2]] <- c(0.03, 0.05, 0.10, 0.13, 0.15)
p.trues.5[[3]] <- c(0.07, 0.09, 0.12, 0.15, 0.30)
p.true.5 <- rbind(p.trues.5[[1]],p.trues.5[[2]],p.trues.5[[3]])


p.trues.6 <- list()
p.trues.6[[1]] <- c(0.05, 0.08, 0.10, 0.13, 0.15)
p.trues.6[[2]] <- c(0.09, 0.12, 0.15, 0.30, 0.45)
p.trues.6[[3]] <- c(0.15, 0.30, 0.45, 0.50, 0.60)
p.true.6 <- rbind(p.trues.6[[1]],p.trues.6[[2]],p.trues.6[[3]])


p.trues.7 <- list()
p.trues.7[[1]] <- c(0.07, 0.10, 0.12, 0.15, 0.30)
p.trues.7[[2]] <- c(0.15, 0.30, 0.45, 0.52, 0.60)
p.trues.7[[3]] <- c(0.30, 0.50, 0.60, 0.65, 0.75)
p.true.7 <- rbind(p.trues.7[[1]],p.trues.7[[2]],p.trues.7[[3]])


p.trues.8 <- list()
p.trues.8[[1]] <- c(0.02, 0.10, 0.15, 0.50, 0.60)
p.trues.8[[2]] <- c(0.05, 0.12, 0.30, 0.55, 0.70)
p.trues.8[[3]] <- c(0.08, 0.15, 0.45, 0.60, 0.80)
p.true.8 <- rbind(p.trues.8[[1]],p.trues.8[[2]],p.trues.8[[3]])


p.trues.9 <- list()
p.trues.9[[1]] <- c(0.10, 0.12, 0.30, 0.40, 0.45)
p.trues.9[[2]] <- c(0.15, 0.30, 0.37, 0.43, 0.48)
p.trues.9[[3]] <- c(0.30, 0.37, 0.42, 0.47, 0.52)
p.true.9 <- rbind(p.trues.9[[1]],p.trues.9[[2]],p.trues.9[[3]])


p.trues.10 <- list()
p.trues.10[[1]] <- c(0.01, 0.03, 0.06, 0.08, 0.10)
p.trues.10[[2]] <- c(0.04, 0.07, 0.12, 0.16, 0.30)
p.trues.10[[3]] <- c(0.08, 0.10, 0.15, 0.30, 0.50)
p.true.10 <- rbind(p.trues.10[[1]],p.trues.10[[2]],p.trues.10[[3]])

p.trues.11 <- list()
p.trues.11[[1]] <- c(0.06, 0.10, 0.15, 0.30, 0.50)
p.trues.11[[2]] <- c(0.10, 0.30, 0.50, 0.70, 0.80)
p.trues.11[[3]] <- c(0.50, 0.60, 0.70, 0.80, 0.90)
p.true.11 <- rbind(p.trues.11[[1]],p.trues.11[[2]],p.trues.11[[3]])

p.trues.12 <- list()
p.trues.12[[1]] <- c(0.05, 0.12, 0.20, 0.30, 0.40)
p.trues.12[[2]] <- c(0.10, 0.20, 0.30, 0.40, 0.50)
p.trues.12[[3]] <- c(0.30, 0.42, 0.52, 0.62, 0.70)
p.true.12 <- rbind(p.trues.12[[1]],p.trues.12[[2]],p.trues.12[[3]])

p.trues.13 <- list()
p.trues.13[[1]] <- c(0.12, 0.20, 0.30, 0.40, 0.60)
p.trues.13[[2]] <- c(0.20, 0.30, 0.40, 0.50, 0.67)
p.trues.13[[3]] <- c(0.42, 0.52, 0.62, 0.70, 0.80)
p.true.13 <- rbind(p.trues.13[[1]],p.trues.13[[2]],p.trues.13[[3]])

p.trues.14 <- list()
p.trues.14[[1]] <- c(0.04, 0.06, 0.08, 0.20, 0.30)
p.trues.14[[2]] <- c(0.10, 0.20, 0.30, 0.50, 0.67)
p.trues.14[[3]] <- c(0.30, 0.42, 0.52, 0.70, 0.80)
p.true.14 <- rbind(p.trues.14[[1]],p.trues.14[[2]],p.trues.14[[3]])

p <- array(c(p.true.1,p.true.2,p.true.3,p.true.4,p.true.5,p.true.6,p.true.7,p.true.8,p.true.9,p.true.10,p.true.11,p.true.12,p.true.13,p.true.14), dim = c(3,5,14))
```



 
```{r}
for (j in 1:14) {
  

simulate <- function(i){
 
   res.CFO <- CFO.simu.fn(target, p[,,j], prelim=0, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=seeds[i])
   
   res.BOIN <- boin.simu.fn(target, p[,,j], ncohort, cohortsize, seed=seeds[i])
 
   
   res <- c(res.CFO$correct,
            as.numeric(sub("%","",res.CFO$npercent))/100,
            res.CFO$ntox,
            as.numeric(sub("%","",res.CFO$ptoxic))/100,
            res.BOIN$correct,
            as.numeric(sub("%","",res.BOIN$npercent))/100,
            res.BOIN$ntox,
            as.numeric(sub("%","",res.BOIN$ptoxic))/100)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
}
```


```{r}
for (i in 1:20) {
     res.CFO <- CFO.simu.fn(target, p[,,1], prelim=0, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=seeds[i])
   
   res.BOIN <- boin.simu.fn(target, p[,,1], ncohort, cohortsize, seed=seeds[i])
 
   
   res <- c(res.CFO$correct,
            as.numeric(sub("%","",res.CFO$npercent))/100,
            res.CFO$ntox,
            as.numeric(sub("%","",res.CFO$ptoxic))/100,
            res.BOIN$correct,
            as.numeric(sub("%","",res.BOIN$npercent))/100,
            res.BOIN$ntox,
            as.numeric(sub("%","",res.BOIN$ptoxic))/100)
   cat(res,'\n')
}
```




```{r}
#Specifiy the possible orderings from Section 3.3.
orders<-matrix(nrow=6,ncol=15)
orders[1,]<-c(1,4,7,10,13,2,5,8,11,14,3,6,9,12,15)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
orders[3,]<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)
orders[4,]<-c(1,4,2,7,5,3,10,8,6,13,11,9,14,12,15)
orders[5,]<-c(1,2,4,7,5,3,6,8,10,13,11,9,12,14,15)
orders[6,]<-c(1,4,2,3,5,7,10,8,6,9,11,13,14,12,15)

#Specify the skeleton values.
skeleton<-getprior(0.03,0.30,13,15)

#Initial guesses of toxicity probabilities for each ordering.
alpha<-getwm(orders,skeleton)
  
#We consider all orders to be equally likely prior to the study.
prior.o<-rep(1/6,6)

#Initial escalation in Stage 1 proceeds according to the zones in Figure 1.
#Single patient cohorts are used.
x0<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)

#Number of patients used to define stopping rule
stop<-61

#Maximum sample size.
n<-60

#The target toxicity rate
theta<-0.30

#Definition of acceptable DLT rates
tox.range<-0.05

#pocrm.sim(r=c(p.true.1),alpha=alpha,prior.o=prior.o,x0=x0,stop=61,n=60,theta=0.3, nsim=1,tox.range=tox.range)
```


```{r}
for (j in 1:14) {
  

simulate <- function(i){
   
   res.dfcomb <- dfcomb.simu.fn(ndose_a1=3, ndose_a2=5, p_tox=p[,,j], target=0.30, target_min=0.20, target_max=0.40, 
                                prior_tox_a1=prior_tox_a1, prior_tox_a2=prior_tox_a2, n_cohort=20, cohort=3, tite=FALSE, 
                                time_full=0, poisson_rate=0, c_e=0.85, c_d=0.45, c_stop=0.95, c_t=0.5,
                                c_over=0.25, cmin_overunder=2, cmin_mtd=3, cmin_recom=1, startup=1, alloc_rule=1, early_stop=1,
                                nburn=2000, niter=5000, seed=seeds[i])
 
   
   res <- c(res.dfcomb$correct,
            res.dfcomb$npercent,
            res.dfcomb$ntox,
            res.dfcomb$ptoxic)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
}
```


```{r}
for (j in 1:14) {
simulate <- function(i){
   
   res.pocrm <- pocrm.sim(c(p[,,j]), alpha, prior.o, x0, 60, theta, seed=seeds[i])
    
   
   res <- c(res.pocrm$correct,
            res.pocrm$npercent,
            res.pocrm$ntox,
            res.pocrm$ptoxic)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
}
```



















