
---
title: "compare"
output: html_document
date: '2022-07-12'
---

```{r}
source("2D_CFO_MTD.R")
source("pocrm.R")
library(parallel)

target <- 0.30
ncohort <- 20
cohortsize <- 3
init.level.A <- 1
init.level.B <- 1
prior_a1 = c(0.1, 0.2, 0.3)
prior_a2 = c(0.1, 0.2, 0.3, 0.4, 0.5)
prior_tox_a1 = c(0.2, 0.3, 0.4)
prior_tox_a2 = c(0.1, 0.2, 0.3, 0.4, 0.5)
order <- c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)
seeds <- 1:5000

add.args <- list(alp.prior=target, bet.prior=1-target)
```

```{r}
set.seed(1)
p <- random(3,0.01)
res.CFO <- CFO.simu.fn(target, p, prelim=1, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=1)
sum(res.CFO$dose.ns)
```



# ```{r}
#
# simulate1 <- function(i){
#
#   res.CFO <- CFO.simu.fn(target, p.true.1, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=seeds[i])
#
#   res.BOIN <- get.oc.comb(target, p.true.1, ncohort, cohortsize, ntrial=1, seed=seeds[i])
#
#
#   res.dfcomb <- dfcomb.simu.fn(ndose_a1=3, ndose_a2=5, p_tox=p.true.1, target=0.30, target_min=0.20, target_max=0.40,
#                                prior_tox_a1=prior_tox_a1, prior_tox_a2=prior_tox_a2, n_cohort=20, cohort=3, tite=FALSE,
#                                nsim=1, c_over=1, cmin_overunder=3, cmin_recom=1, startup=1, alloc_rule=1, early_stop=1, seed=seeds[i])
#
#
#   res <- c(res.CFO$correct,
#            as.numeric(sub("%","",res.CFO$npercent))/100,
#            res.CFO$ntox,
#            as.numeric(sub("%","",res.BOIN$pcs))/100,
#            as.numeric(sub("%","",res.BOIN$npercent))/100,
#            res.BOIN$totaltox,
#            res.dfcomb$correct,
#            as.numeric(sub("%","",res.dfcomb$npercent))/100,
#            res.dfcomb$ntox)
#   return(res)
# }
#
# r <- mclapply(1:5000, simulate1, mc.cores = 10)
# results <- Reduce("+", r)
# results/5000
# ```

```{r}
simulate <- function(i){
  
   set.seed(seeds[i])
   p <- random(4,4,nMTD=3,0.01)
 
   res.CFO <- CFO.simu.fn(target, p, prelim=0, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=seeds[i])
   
   res.BOIN <- boin.simu.fn(target, p, ncohort, cohortsize, seed=seeds[i])
 
   
   res <- c(res.CFO$correct,
            as.numeric(sub("%","",res.CFO$npercent))/100,
            res.CFO$ntox,
            as.numeric(sub("%","",res.CFO$ptoxic))/100,
            res.BOIN$correct,
            as.numeric(sub("%","",res.BOIN$npercent))/100,
            res.BOIN$ntox,
            as.numeric(sub("%","",res.BOIN$ptoxic))/100)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
```


```{r}
simulate <- function(i){
  
  set.seed(seeds[i])
  p <- random(4,4,nMTD=3,0.01)
 
  res.dfcomb <- dfcomb.simu.fn(ndose_a1=3, ndose_a2=5, p_tox=p.true.1, target=0.30, target_min=0.20, target_max=0.40,
                              prior_tox_a1=prior_tox_a1, prior_tox_a2=prior_tox_a2, n_cohort=20, cohort=3, tite=FALSE,c_over=1, cmin_overunder=3,                                        cmin_recom=1, startup=1, alloc_rule=1, early_stop=1, seed=seeds[i])
  
  
  res <- c(res.dfcomb$correct,
           as.numeric(sub("%","",res.dfcomb$npercent))/100,
           res.dfcomb$ntox)
  return(res)
}


r <- mclapply(1:5000, simulate, mc.cores = 40)
results <- Reduce("+", r)
results/5000
```



```{r}
prior_tox_a1 = c(0.2, 0.3, 0.4)
prior_tox_a2 = c(0.1, 0.2, 0.3, 0.4, 0.5)

simulate <- function(i){
   set.seed(seeds[i])
   p <- random(4,4,nMTD=3,0.01)
   res.dfcomb <- dfcomb.simu.fn(ndose_a1=4, ndose_a2=4, p_tox=p, target=0.30, target_min=0.20, target_max=0.40, 
                                prior_tox_a1=prior_tox_a1, prior_tox_a2=prior_tox_a2, n_cohort=20, cohort=3, tite=FALSE, 
                                time_full=0, poisson_rate=0, c_e=0.85, c_d=0.45, c_stop=0.95, c_t=0.5,
                                c_over=0.25, cmin_overunder=2, cmin_mtd=3, cmin_recom=1, startup=1, alloc_rule=1, early_stop=1,
                                nburn=2000, niter=5000, seed=seeds[i])
 
   
   res <- c(res.dfcomb$correct,
            res.dfcomb$npercent,
            res.dfcomb$ntox,
            res.dfcomb$ptoxic)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
```


```{r}
simulate <- function(i){
 
   res.CFO <- CFO.simu.fn(target, p.true.1, ncohort, cohortsize, init.level.A, init.level.B, add.args=add.args, seed=seeds[i])
   
   res.BOIN <- get.oc.comb(target, p.true.1, ncohort, cohortsize, ntrial=1, seed=seeds[i])
 
   
   res <- c(res.CFO$correct,
            as.numeric(sub("%","",res.CFO$npercent))/100,
            res.CFO$ntox,
            as.numeric(sub("%","",res.BOIN$pcs))/100,
            as.numeric(sub("%","",res.BOIN$npercent))/100,
            res.BOIN$totaltox)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 results/5000
```




```{r}
#Specifiy the possible orderings from Section 3.3.
orders<-matrix(nrow=6,ncol=15)
orders[1,]<-c(1,4,7,10,13,2,5,8,11,14,3,6,9,12,15)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
orders[3,]<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)
orders[4,]<-c(1,4,2,7,5,3,10,8,6,13,11,9,14,12,15)
orders[5,]<-c(1,2,4,7,5,3,6,8,10,13,11,9,12,14,15)
orders[6,]<-c(1,4,2,3,5,7,10,8,6,9,11,13,14,12,15)

#Specify the skeleton values.
skeleton<-getprior(0.03,0.30,13,15)

#Initial guesses of toxicity probabilities for each ordering.
alpha<-getwm(orders,skeleton)

#We consider all orders to be equally likely prior to the study.
prior.o<-rep(1/6,3)

#Initial escalation in Stage 1 proceeds according to the zones in Figure 1.
#Single patient cohorts are used.
x0<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)

#Number of patients used to define stopping rule
stop<-61

#Maximum sample size.
n<-60

#The target toxicity rate
theta<-0.30

#Definition of acceptable DLT rates
tox.range<-0.05

```



```{r}
#Specifiy the possible orderings from Section 3.3.
orders<-matrix(nrow=6,ncol=16)

orders[1,]<-c(1,5,9,13,2,6,10,14,3,7,11,15,4,8,12,16)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16)
orders[3,]<-c(1,2,5,3,6,9,4,7,10,13,8,11,14,12,15,16)
orders[4,]<-c(1,5,2,9,6,3,13,10,7,4,14,11,8,15,12,16)
orders[5,]<-c(1,2,5,9,6,3,4,7,10,13,14,11,8,12,15,16)
orders[6,]<-c(1,5,2,3,6,9,13,10,7,4,8,11,14,15,12,16)

#Specify the skeleton values.
skeleton<-getprior(0.03,0.30,13,16)

#Initial guesses of toxicity probabilities for each ordering.
alpha<-getwm(orders,skeleton)

#We consider all orders to be equally likely prior to the study.
prior.o<-rep(1/6,6)

#Initial escalation in Stage 1 proceeds according to the zones in Figure 1.
#Single patient cohorts are used.
x0<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15,16)

#Number of patients used to define stopping rule
stop<-61

#Maximum sample size.
n<-60

#The target toxicity rate
theta<-0.30

#Definition of acceptable DLT rates
tox.range<-0.05
```





```{r}
#Specifiy the possible orderings from Section 3.3.
orders<-matrix(nrow=6,ncol=20)

orders[1,]<-c(1,5,9,13,17,2,6,10,14,18,3,7,11,15,19,4,8,12,16,20)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20)
orders[3,]<-c(1,2,5,3,6,9,4,7,10,13,8,11,14,17,12,15,18,16,19,20)
orders[4,]<-c(1,5,2,9,6,3,13,10,7,4,17,14,11,8,18,15,12,19,16,20)
orders[5,]<-c(1,2,5,9,6,3,4,7,10,13,17,14,11,8,12,15,18,19,16,20)
orders[6,]<-c(1,5,2,3,6,9,13,10,7,4,8,11,14,17,18,15,12,16,19,20)

#Specify the skeleton values.
skeleton<-getprior(0.03,0.30,13,20)

#Initial guesses of toxicity probabilities for each ordering.
alpha<-getwm(orders,skeleton)

#We consider all orders to be equally likely prior to the study.
prior.o<-rep(1/6,6)

#Initial escalation in Stage 1 proceeds according to the zones in Figure 1.
#Single patient cohorts are used.
x0<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15)

#Number of patients used to define stopping rule
stop<-61

#Maximum sample size.
n<-60

#The target toxicity rate
theta<-0.30

#Definition of acceptable DLT rates
tox.range<-0.05
```



```{r}
simulate <- function(i){
   
  set.seed(seeds[i])
  p <- random(4,4,nMTD=3,0.01)
  
  res.pocrm <- pocrm.sim(c(p), alpha, prior.o, x0, 60, theta, seed=seeds[i])
    
   
   res <- c(res.pocrm$correct,
            res.pocrm$npercent,
            res.pocrm$ntox,
            res.pocrm$ptoxic)
   return(res)
 }
 
 
 r <- mclapply(1:5000, simulate, mc.cores = 40)
 results <- Reduce("+", r)
 cat(results/5000, '\n')
```




