---
title: "random"
output: html_document
date: '2022-08-10'
---

```{r}
orders<-matrix(nrow=6,ncol=15)
orders[1,]<-c(1,4,7,10,13,2,5,8,11,14,3,6,9,12,15)
orders[2,]<-c(1,2,3,4,5,6,7,8,9,10,11,12,13,14,15)
orders[3,]<-c(1,2,4,3,5,7,6,8,10,9,11,13,12,14,15) #
orders[4,]<-c(1,4,2,7,5,3,10,8,6,13,11,9,14,12,15) #
orders[5,]<-c(1,2,4,7,5,3,6,8,10,13,11,9,12,14,15)
orders[6,]<-c(1,4,2,3,5,7,10,8,6,9,11,13,14,12,15)

```



```{r}
runif_gap <- function(n,min, max, e){
  repeat{
    s <- sort(runif(n,min,max))
    mindiff <- min(diff(s))
    if (mindiff >= e){
      break
    }
  }
  return(s)
}
```


```{r}
shuffle <- function(p){
  p <- c(p[1],sample(p[2:3]),sample(p[4:6]),sample(p[7:9]),sample(p[10:12]),sample(p[13:14]),p[15])
  return(p)
}

# shuffle <- function(p){
#   p <- c(p[1],sample(p[2:3]),sample(p[4:6]),sample(p[7:10]),sample(p[11:13]),sample(p[14:15]),p[16])
#   return(p)
# }
```


```{r}
random <- function(phi, nA, nB, e, orders, nMTD, seed){
  set.seed(seed)
  n <- nA*nB
  k <- sample(1:(n-nMTD+1), 1)
  first <- runif(k-1, 0, phi-e)
  second <- runif(n-k-nMTD+1, phi+e, 1)
  p <- shuffle(sort(c(first, rep(phi,nMTD), second)))
  # return(p)
  return(matrix(p[orders], nA, nB))
}
```


```{r}
p <- random(0.3,3,5,0.05,orders[3,],2,seed=3)
p
```


