---
title: "sampling"
output: html_document
date: '2022-09-05'
---


```{r}
sampling <- function(phi, ndose.A, ndose.B, tys, tns, n, lower, upper){
  samples <- as.list(numeric(ndose.A*ndose.B))
  dim(samples) <- c(ndose.A,ndose.B)
  for (i in 1:ndose.A) {
    for (j in 1:ndose.B) {
      nsamples <- 0
      if (i==1 & j==1){
        next
      } else {
        
        if (i==1){
          while (nsamples<n) {
            pl <- rbeta(1,phi+tys[i,j-1],1-phi+tns[i,j-1]-tys[i,j-1])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pl<pc){
              samples[[i,j-1]] <- c(samples[[i,j-1]],pl)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        } else if (j==1){
          while (nsamples<n) {
            pd <- rbeta(1,phi+tys[i-1,j],1-phi+tns[i-1,j]-tys[i-1,j])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pd<pc){
              samples[[i-1,j]] <- c(samples[[i-1,j]],pd)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        } else {
          while (nsamples<n) {
            pl <- rbeta(1,phi+tys[i,j-1],1-phi+tns[i,j-1]-tys[i,j-1])
            pd <- rbeta(1,phi+tys[i-1,j],1-phi+tns[i-1,j]-tys[i-1,j])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pl<pc & pd<pc){
              samples[[i,j-1]] <- c(samples[[i,j-1]],pl)
              samples[[i-1,j]] <- c(samples[[i-1,j]],pd)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        }
      }
    }
  }
  
  p <- matrix(0,ndose.A,ndose.B)
  for (i in 1:ndose.A) {
    for (j in 1:ndose.B) {
      p[i,j] <- length(samples[[i,j]][samples[[i,j]]>lower & samples[[i,j]]<upper])/length(samples[[i,j]])
    }
  }
  return(p)
}
```

```{r}
sampling <- function(phi, ndose.A, ndose.B, tys, tns, n, lower, upper){
  samples <- as.list(numeric(ndose.A*ndose.B))
  dim(samples) <- c(ndose.A,ndose.B)
  p <- matrix(0,ndose.A,ndose.B)
  for (i in 1:ndose.A) {
    for (j in 1:ndose.B) {
      nsamples <- 0
      if (i==1 & j==1){
        next
      } else {
        
        if (i==1){
          while (nsamples<n) {
            pl <- rbeta(1,phi+tys[i,j-1],1-phi+tns[i,j-1]-tys[i,j-1])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pl<pc){
              samples[[i,j-1]] <- c(samples[[i,j-1]],pl)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        } else if (j==1){
          while (nsamples<n) {
            pd <- rbeta(1,phi+tys[i-1,j],1-phi+tns[i-1,j]-tys[i-1,j])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pd<pc){
              samples[[i-1,j]] <- c(samples[[i-1,j]],pd)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        } else {
          while (nsamples<n) {
            pl <- rbeta(1,phi+tys[i,j-1],1-phi+tns[i,j-1]-tys[i,j-1])
            pd <- rbeta(1,phi+tys[i-1,j],1-phi+tns[i-1,j]-tys[i-1,j])
            pc <- rbeta(1,phi+tys[i,j],1-phi+tns[i,j]-tys[i,j])
            if (pl<pc & pd<pc){
              samples[[i,j-1]] <- c(samples[[i,j-1]],pl)
              samples[[i-1,j]] <- c(samples[[i-1,j]],pd)
              samples[[i,j]] <- c(samples[[i,j]],pc)
              nsamples <- nsamples + 1
            }
          }
        }
      }
      
      p[i,j] <- length(samples[[i,j]][samples[[i,j]]>lower & samples[[i,j]]<upper])/length(samples[[i,j]])
    }
  }

  return(p)
}
```

```{r}
line.sampling <- function(phi, ndose, tys, tns, n, lower, upper){
  samples <- as.list(numeric(ndose))
  p <- replicate(ndose, 0)
  nsamples <- 0
  while (nsamples<n) {
    s <- replicate(ndose, 0)
    for (i in 1:ndose) {
      s[i] <- rbeta(1,phi+tys[i],1-phi+tns[i]-tys[i])
    }
    if (all(diff(s) >= 0)){
      for (j in 1:ndose) {
        samples[[j]] <- c(samples[[j]],s[j])
      }
      nsamples <- nsamples + 1
    } else {
      next
    }
  }
  for (k in 1:ndose) {
    p[k] <- length(samples[[k]][samples[[k]]>lower & samples[[k]]<upper])/length(samples[[k]])
  }
  return(p)
}
```

```{r}
cross.sampling <- function(phi, ndose.A, ndose.B, tys, tns, n, lower, upper){
  p <- matrix(0,ndose.A,ndose.B)
  for (i in 1:ndose.A) {
    p[i,] <- p[i,] + line.sampling(phi, ndose.B, tys[i,], tns[i,], n, lower, upper)
  }
  for (j in 1:ndose.B) {
    p[,j] <- p[,j] + line.sampling(phi, ndose.A, tys[,j], tns[,j], n, lower, upper)
  }
  return(p)
}
```

```{r}
sampling(0.3, 3, 5, tys, tns, 500, 0.2, 0.4)
```

```{r}
sampling(0.3, 3, 5, tys, tns, 500, 0.2, 0.4)
```



```{r}
cross.sampling(0.3, 3, 5, tys, tns, 500, 0.2, 0.4)
```


